### ISSUE TITLE
description

### ISSUE THREAD

**Issue by star-buck** [plasma-extensions/plasma-widget-extended-volume-mixer#1]
Same full sidepanel size than the notification bar or this one, but with these:
- Align all elements towards bottom, so free space is above
- show input and output volume sliders default with arrow next to them to reveal routing devices and ports
- put any application currently streaming audio below the two main outputs with the same dropdown, so one can easily route them individually to certain ports/devices

**Comment by UriHerrera** [comment]
This is a a separate widget right? not an addition to the quick-controls widget.

**Comment by star-buck** [comment]
Yes, seperate.

**Comment by UriHerrera** [comment]
![](http://i.imgur.com/9D2uKIM.png)
- Each slider controls a separate stream; Output, Input and Applications which have a slider each. 
- The sound preferences is accessible through the hamburger menu next to the output slider.
- Each new application stream should be added below the input.
- Each area can be expanded separately.
- The selection of the port in the Outputs area affects the port where applications stream their audio to.

**Comment by star-buck** [comment]
can an app audio stream be routed to a specific port, like line out?

**Comment by UriHerrera** [comment]
> can an app audio stream be routed to a specific port, like line out?

I haven't seen any examples that it's possible to but neither that it's not possible.  I think this is a hint: http://superuser.com/questions/903390/how-can-two-applications-read-from-the-same-digital-sound-input-in-linux-alsa though this is for ALSA and not PulseAudio.

I know for a fact that two applications can't use the same device at the same time and that happens in Windows and Linux. But of course Linux being more flexible that'd only have to be implemented into the widget to see if it works for PA.

**Comment by azubieta** [comment]
I asked in the pulse audio IRC channel and got this reply:

> Ports are supposed to be mutually exclusive outputs of a given sink, so might not be possible to have multiple sink inputs concurrently going to different ports

So giving the option of picking which port to use will end in changing the default port for the device, which also will affect other applications using that device.

**Comment by azubieta** [comment]
A preview, still missing the applications icon.
Question: The app icon will work as a "mute" button ?

![1](https://cloud.githubusercontent.com/assets/1138094/19424848/c8cfe5ba-93fa-11e6-8257-c8fb67c4ffad.png)

**Comment by UriHerrera** [comment]
> Question: The app icon will work as a "mute" button ?

I'd say rather make the speaker icon a button which does the muting.

**Comment by azubieta** [comment]
So the app icon and its name will be placed above the controller?

**Comment by UriHerrera** [comment]
> So the app icon and its name will be placed above the controller?

No it'd be below the slider, I used the word Stream but here's more clear.

![](http://i.imgur.com/fbydsb1.png)

# 

Here the app icon is a toggleable button which mutes or unmutes the stream. If the stream is muted the icon is grayed out and it's opacity is 50%.

**Comment by azubieta** [comment]
This is it! Also the master branch is up to date.
The Compact Representation of the plasmoid has the same behavior  that the current plasma-pa plasmoid. So yo can scroll to change the current volumen, middle click to mute, etc.

![1](https://cloud.githubusercontent.com/assets/1138094/19489665/22d42bee-953a-11e6-8f43-2d92539e1c78.png)
